name: Build and Publish Python Package

on:
  push:
    tags:
      - "v*" # Trigger on version tags
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write # Required for trusted publishing

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build pytest
          pip install -e .

      - name: Run tests
        run: |
          pytest tests/

      - name: Build package
        run: |
          python -m build

      - name: Check dist contents
        run: |
          python -m pip install twine
          twine check dist/*

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/') # Only publish on tag pushes
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
